# Generated by Django 3.1.7 on 2021-03-03 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210303_0918'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_star', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='star',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.starstudent'),
        ),
    ]
