# Generated by Django 3.1.7 on 2021-03-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210303_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='star',
        ),
        migrations.AddField(
            model_name='student',
            name='is_star',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='StarStudent',
        ),
    ]
