# Generated by Django 3.1.7 on 2021-03-05 00:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210304_1746'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='student',
            managers=[
                ('your_teachers', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='teacher',
            managers=[
                ('your_students', django.db.models.manager.Manager()),
            ],
        ),
    ]
