# Generated by Django 3.1.7 on 2021-03-05 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210305_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_star',
        ),
        migrations.AddField(
            model_name='student',
            name='like',
            field=models.ManyToManyField(related_name='liked_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
