# Generated by Django 3.1.7 on 2021-03-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210305_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='like',
        ),
        migrations.AddField(
            model_name='teacher',
            name='like',
            field=models.ManyToManyField(related_name='liked_student', to='app.Student'),
        ),
    ]
