# Generated by Django 3.1.7 on 2021-03-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210306_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='like',
        ),
        migrations.AddField(
            model_name='student',
            name='is_star',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
