# Generated by Django 3.1.7 on 2021-03-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210307_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_star',
        ),
        migrations.AddField(
            model_name='teacher',
            name='star_students',
            field=models.ManyToManyField(related_name='star_students', to='app.Student'),
        ),
    ]
