# Generated by Django 3.1.7 on 2021-03-07 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210307_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='star_students',
        ),
        migrations.AddField(
            model_name='student',
            name='star_students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='star_students', to='app.teacher'),
        ),
    ]
